import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 440, height: 920 } });
p.on('pageerror', (e) => console.log('[pageerror]', e.message));
p.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warn') console.log('[' + m.type() + ']', m.text()); });
await p.goto('http://localhost:5173/');
await p.waitForTimeout(2000);
await p.evaluate(() => localStorage.clear());
await p.reload();
await p.waitForTimeout(1800);
console.log('menu buttons:', await p.locator('.menu-btn').allTextContents());
await p.click('.menu-btn >> text=开始新的一夜');
await p.waitForTimeout(3000);
console.log('screen-content innerHTML len:', await p.evaluate(() => document.querySelector('.screen-content')?.innerHTML.length));
console.log('screen text:', await p.evaluate(() => document.querySelector('.screen-content')?.textContent?.slice(0, 80)));
console.log('chat-screen?', await p.locator('.chat-screen').count());
console.log('msg rows?', await p.locator('.msg-row').count());
await p.screenshot({ path: 'qa/dbg2.png' });
await b.close();
